### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by TSnake41** [Andre-LA/raylib-nelua#20]
raylib-nelua is an interesting binding and having a logo can be nice.

Here is a logo proposal
![image](https://user-images.githubusercontent.com/8642647/102025877-0b13bc00-3d9b-11eb-8551-8b079066b739.png)

I made a program to draw this logo that uses https://github.com/TSnake41/raylib-lua 
```lua
local lua_color = rl.new("Color", 0x14, 0x43, 0x89, 255)

local width, height = 800, 450

rl.SetConfigFlags(rl.FLAG_VSYNC_HINT)
rl.InitWindow(800, 450, "raylib [shapes] example - basic shapes drawing")

while not rl.WindowShouldClose() do
  rl.BeginDrawing()

  rl.ClearBackground(rl.RAYWHITE)

  rl.DrawRectangle(width / 2 - 128, height / 2 - 128, 256, 256, lua_color)
  rl.DrawRectangle(width / 2 - 112, height / 2 - 112, 224, 224, rl.RAYWHITE)
  rl.DrawText("raylib", width / 2 - 44, height / 2 + 24, 50, lua_color)
  rl.DrawText("NeLua", width / 2 - 49, height / 2 + 64, 50, lua_color)

  rl.DrawText("this is NOT a texture!", 350, 370, 10, rl.GRAY)

  rl.EndDrawing()
end

rl.CloseWindow()
```

**Comment by Andre-LA** [comment]
Thanks :D

Once I get time I'll add the logo image (maybe as .svg) and add the logo code example

**Comment by Andre-LA** [comment]
[Logo example added](https://github.com/Andre-LA/raylib-nelua/blob/master/examples/shapes/logo-raylib-nelua.nelua) and also on the README, it's works both on Github's Dark theme and Light theme in my browser (Firefox 83):

![image](https://user-images.githubusercontent.com/8538122/102097198-5d3cf780-3e04-11eb-9bf2-08ee7f9c0952.png)

The logo image on the README uses an [.svg file](https://github.com/Andre-LA/raylib-nelua/blob/master/raylib-nelualogo.svg) saved from Inkscape.

The color comes from the Nelua logo.
