### ISSUE TITLE
Array out of bounds error on 2d camera

### ISSUE THREAD

**Issue by edubart** [Andre-LA/raylib-nelua#8]
Since a recent commit in Nelua the compiler catches array out of bounds index errors at runtime by default (this can be disabled with `-Pnochecks` for improving performance).

When running 2d-camera example we get a crash with `array index: position out of bounds`.
The reason is in this line https://github.com/Andre-LA/raylib-nelua-mirror/blob/master/examples/core/2d-camera.nelua#L102 where a `<` is missing in the for loop.

**Comment by Andre-LA** [comment]
Oh, Thanks!
